apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-db
spec:
  selector:
    matchLabels:
      app: storage-db
  template:
    metadata:
      labels:
        app: storage-db
    spec:
      containers:
      - name: storage-db
        image: postgres:15.5-alpine
        env: 
        - name: PGUSER
          value: E-Corp
        - name: POSTGRES_DB 
          value: E-Corp
        - name: POSTGRES_USER
          value: E-Corp
        - name: POSTGRES_PASSWORD 
          value: Password123
--- 
apiVersion: v1
kind: Service
metadata:
  name: e-corp-db
spec:
  selector:
    app: e-corp-db
  ports:
  - port: 5432
    targetPort: 5432
