apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: user_authentication
        - name: POSTGRES_USER
          value: user_authentication
        - name: POSTGRES_PASSWORD
          value: password123
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: database-struct
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: database-struct
        configMap:
          name: database
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - name: database
    protocol: TCP
    port: 5432
    targetPort: 5432
