apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      imagePullSecrets: 
      - name: regcred
      containers:
      - name: sre-challenge
        image: thomasmldejong/sre-challenge:sre-challenge
        imagePullPolicy: Always
        env:
        - name: DB_HOST 
          value: postgresql
        - name: DB_PORT
          value: '5432' 
        - name: DB_NAME
          value: user_authentication
        - name: DB_USER
          value: user_authentication
        - name: DB_PASSWORD 
          value: password123
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  selector:
    app: application
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000