apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: sre-challenge
        image: webapp
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST 
          value: {{ .Values.DB_HOST }}
        - name: DB_PORT
          value: {{ quote .Values.DB_PORT }}
        - name: DB_NAME
          value: {{ .Values.DB_NAME }}
        - name: DB_USER
          value: {{ .Values.DB_USER }}
        - name: DB_PASSWORD 
          value: {{ .Values.DB_PASSWORD }}
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  selector:
    app: application
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000 
